---
layout: Resume
title: Erin Hu's Resume
---
# Erin Hu

<div id="webaddress">
| <a href="https://www.linkedin.com/in/erinhu0619/">My Linkdin page</a>
</div>


## Currently

Senior student at BYU - Idaho

### Specialized in
Hard Skill: Data Analysis(R studio, SQL, Power BI), Data Visualization(Tableau), Microsoft Excel

Soft Skills: Cross-functional Team Collaboration, Strong Attention to Detail, Analytical Thinking, Problem Solving



## Education

`2021-2025`
__Brigham Young University, Idaho__

- Statistics Major with a Data Science Minor


## Occupation

`Sep 2024 - Present`
__Data Visualization Specialist 2__ , __BYUI__, Idaho
- Initiated new visualized statistics, leading to catching discrepancies between sources using Power BI and
Presenting indicators on a weekly basis
- Generated time series charts and KPI dashboards to monitor annual performance, collaborating with
executive leadership to enhance workflow strategies through the utilization of DAX and Query

`April 2024 - Sep 2024` __Business Analyst Intern__ , 
__The Church of Jesus Christ of Latter Day Saints__, Utah

- Processed 4 million rows of data and organized a comprehensive data dictionary
- Collaborated with various departments and facilitate a strong connection
- Designed a Power BI dashboard to detect utility bill anomalies and reported to stakeholders
- Contributed to analytical projects, data validation, and assisted in data interpretation tasks


